name: anythingllm

networks:
  anything-llm:
    name: chroma_network
    external: true

services:
  anything-llm:
    container_name: anythingllm
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile_dev
      args:
        ARG_UID: ${A_UID}
        ARG_GID: ${A_GID} 
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
      - "./:/app/docker"
      - "../server:/app/server"
      - "../frontend:/app/frontend"
      - "../collector:/app/collector"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
      - "3000:3000"
      - "5173:5173"
      - "8888:8888"
    env_file:
      - .env
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"
